# Generated by Django 2.1.15 on 2020-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_auto_20200527_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='District',
            field=models.CharField(choices=[('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Sahiwal', 'Sahiwal')], max_length=100),
        ),
    ]
