# Generated by Django 2.1.15 on 2020-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0003_auto_20200528_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='Country',
            field=models.CharField(choices=[('Pakistan', 'Pakistan'), ('Turkey', 'Turkey'), ('Thailand', 'Thailand'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='edit',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Fe-Male', 'Fe-Male'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='edit',
            name='Martial_Status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='edit',
            name='Religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Christanity', 'Christanity'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='edit',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=30),
        ),
    ]
