# Generated by Django 2.1.15 on 2020-05-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0005_auto_20200528_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='Program',
            field=models.CharField(choices=[('BBIT', 'BBIT'), ('MBIT', 'MBIT')], max_length=50),
        ),
    ]
